groups:
  - name: storyboard_alerts
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(storyboard_api_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second for the last 5 minutes"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(storyboard_api_request_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds"

      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: pg_stat_database_numbackends > 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "Database has {{ $value }} active connections"

      # Redis connection issues
      - alert: RedisConnectionIssues
        expr: redis_connected_clients > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Redis connections"
          description: "Redis has {{ $value }} connected clients"

      # Worker queue backlog
      - alert: WorkerQueueBacklog
        expr: storyboard_worker_queue_size > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Worker queue backlog"
          description: "Worker queue has {{ $value }} pending tasks"

      # Frame generation failures
      - alert: FrameGenerationFailures
        expr: rate(illustration_worker_errors_total{error_type="frame_generation"}[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Frame generation failures"
          description: "Frame generation error rate is {{ $value }} errors per second"

      # Script parsing failures
      - alert: ScriptParsingFailures
        expr: rate(script_worker_errors_total{error_type="parsing"}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Script parsing failures"
          description: "Script parsing error rate is {{ $value }} errors per second"

      # Export generation failures
      - alert: ExportGenerationFailures
        expr: rate(export_worker_errors_total{error_type="export_generation"}[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Export generation failures"
          description: "Export generation error rate is {{ $value }} errors per second"
